name: build
run-name: Build
on: [push]
jobs:
  build-gcc:
    runs-on: ubuntu-latest
    name: Build GCC
    steps:
      - name: Install latest Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"
      - name: Checkout TimZoet/common
        uses: actions/checkout@v3
      - name: Checkout TimZoet/pyreq
        uses: actions/checkout@v3
        with:
          repository: TimZoet/pyreq
          path: packages/pyreq
      - name: Checkout TimZoet/cmake-modules
        uses: actions/checkout@v3
        with:
          repository: TimZoet/cmake-modules
          path: packages/cmake-modules
      - name: Export TimZoet/pyreq
        run: conan export --user timzoet --channel stable packages/pyreq
      - name: Export TimZoet/cmake-modules
        run: conan export --user timzoet --channel stable packages/cmake-modules
