name: build
run-name: Build
on: [push]
jobs:
  build-msvc:
    runs-on: windows-latest
    name: Build MSVC
    steps:
      - name: Install latest Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"
      - name: Conan config install
        run: |
          conan config install --type git https://github.com/TimZoet/conan-config.git
      
      - name: Checkout TimZoet/common
        uses: actions/checkout@v3
        with:
          path: source
      - name: Checkout TimZoet/pyreq
        uses: actions/checkout@v3
        with:
          repository: TimZoet/pyreq
          ref: github_actions
          path: packages/pyreq
      - name: Checkout TimZoet/cmake-modules
        uses: actions/checkout@v3
        with:
          repository: TimZoet/cmake-modules
          ref: github_actions
          path: packages/cmake-modules
      - name: Checkout TimZoet/parsertongue
        uses: actions/checkout@v3
        with:
          repository: TimZoet/parsertongue
          ref: github_actions
          path: packages/parsertongue
      - name: Checkout TimZoet/bettertest
        uses: actions/checkout@v3
        with:
          repository: TimZoet/bettertest
          ref: github_actions
          path: packages/bettertest
          submodules: true
      
      - name: Export TimZoet/pyreq
        run: conan export --user timzoet --channel stable packages/pyreq
      - name: Export TimZoet/cmake-modules
        run: conan export --user timzoet --channel stable packages/cmake-modules
      - name: Export TimZoet/common
        run: conan export --user timzoet --channel stable source
      - name: Export TimZoet/parsertongue
        run: conan export --user timzoet --channel stable packages/parsertongue
      - name: Export TimZoet/bettertest
        run: conan export --user timzoet --channel stable packages/bettertest

      - name: Fix package name
        run: |
          cd source
          python rename.py
      - name: Conan install
        run: |
          mkdir build
          conan install -pr:h=vs2022-release -pr:b=vs2022-release -s build_type=Release -o build_tests=True --build=missing -of=build source
      - name: CMake build
        run: |
          cd build
          cmake -S ../source -B . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=./conan_toolchain.cmake
          cmake --build . --config Release
      - name: Run tests
        run: |
          cd ./build/bin/tests
          .\common_test
  
  build-gcc:
    runs-on: ubuntu-latest
    name: Build GCC
    if: false
    steps:
      - name: Install latest Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"
      - name: Conan config install
        run: conan config install --type git https://github.com/TimZoet/conan-config.git
      
      - name: Checkout TimZoet/common
        uses: actions/checkout@v3
        with:
          path: source
      - name: Checkout TimZoet/pyreq
        uses: actions/checkout@v3
        with:
          repository: TimZoet/pyreq
          ref: github_actions
          path: packages/pyreq
      - name: Checkout TimZoet/cmake-modules
        uses: actions/checkout@v3
        with:
          repository: TimZoet/cmake-modules
          ref: github_actions
          path: packages/cmake-modules
      - name: Checkout TimZoet/parsertongue
        uses: actions/checkout@v3
        with:
          repository: TimZoet/parsertongue
          ref: github_actions
          path: packages/parsertongue
      - name: Checkout TimZoet/bettertest
        uses: actions/checkout@v3
        with:
          repository: TimZoet/bettertest
          ref: github_actions
          path: packages/bettertest
      
      - name: Export TimZoet/pyreq
        run: conan export --user timzoet --channel stable packages/pyreq
      - name: Export TimZoet/cmake-modules
        run: conan export --user timzoet --channel stable packages/cmake-modules
      - name: Export TimZoet/common
        run: conan export --user timzoet --channel stable source
      - name: Export TimZoet/parsertongue
        run: conan export --user timzoet --channel stable packages/parsertongue
      - name: Export TimZoet/bettertest
        run: conan export --user timzoet --channel stable packages/bettertest

      - name: Fix package name
        run: cd source && python rename.py
      - name: Conan install
        run: |
          mkdir build && cd build
          conan install -pr:h=gcc12_1-release -pr:b=gcc12_1-release -s build_type=Release -o build_tests=True --build=missing -of=. ../source
      - name: CMake build
        working-directory: ./build
        run: |
          cmake -S ../source -B . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
          cmake --build . --config Release
      - name: Run tests
        working-directory: ./build/bin/tests
        run: |
          .\common_test -u=*
