name: build
run-name: Build
on: [push]
jobs:
  build-msvc:
    runs-on: windows-latest
    name: Build MSVC
    if: true
    steps:
      - name: Setup Conan
        uses: TimZoet/action-setup-conan
      
      - name: Setup current repository
        uses: TimZoet/action-checkout-current
      - name: Fix package name
        run: |
          cd source
          python rename.py
      
      - name: Retrieve dependencies
        uses: TimZoet/action-retrieve-dependencies
        with:
          conanfile: ${{ github.workspace }}/source/conanfile.py
          profile: ${{ github.workspace }}/source/buildtools/profiles/common-test-vs2022-release
          directory: ${{ github.workspace }}/packages

      - name: Conan install
        run: |
          mkdir build
          conan install -pr:h=${{ github.workspace }}/source/buildtools/profiles/common-test-vs2022-release -pr:b=${{ github.workspace }}/source/buildtools/profiles/common-test-vs2022-release -s build_type=Release --build=missing -of=${{ github.workspace }}/build ${{ github.workspace }}/source
      - name: CMake configure
        run: cmake -S ${{ github.workspace }}/source -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE:FILEPATH=conan_toolchain.cmake
      - name: CMake build
        run: cmake --build . --config Release
        working-directory: ./build
      - name: Run tests
        run: .\common_test
        working-directory: ./build/bin/tests
